# Script to deploy on the Render cloud platfrom

name: Node.js CI

on:
 push:
  branches: [ main ]
pull_request:
 branches: [ main ]

jobs:
 build:
 
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - uses: bounceapp/render-action@0.6.0
   with:
    render-token: ${{secrets.RENDER_API_KEY}}
    github-token: ${{secrets.ACC_API_KEY}} # This is the Github token
    service-id: "
